"""purchase demand comparative

Revision ID: 0029_purchase_demand_comparative
Revises: 0028_tenant_hospital_model
Create Date: 2026-07-04 00:39:00.356543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '0029_purchase_demand_comparative'
down_revision: Union[str, Sequence[str], None] = '0028_tenant_hospital_model'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Only the tables/columns relevant to #137 Phase 1 are kept; unrelated
    # drift detected by autogenerate (payroll/product/journalentry FKs etc.)
    # is stripped — see 5befc82a251f_invoice_cogs_transaction_id.py for the
    # established pattern of trimming autogenerated migrations to intent.
    bind = op.get_bind()

    if not bind.dialect.has_table(bind, 'purchasedemand'):
        op.create_table('purchasedemand',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('tenant_id', sa.Integer(), nullable=False),
        sa.Column('number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('demand_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('required_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('analytic_account_id', sa.Integer(), nullable=True),
        sa.Column('purpose', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('created_by_id', sa.Integer(), nullable=False),
        sa.Column('approved_by_id', sa.Integer(), nullable=True),
        sa.Column('approved_at', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.CheckConstraint("status IN ('draft','approved','converted','closed','cancelled')", name='ck_pd_status'),
        sa.ForeignKeyConstraint(['analytic_account_id'], ['analyticaccount.id'], ),
        sa.ForeignKeyConstraint(['approved_by_id'], ['user.id'], ),
        sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('tenant_id', 'number', name='unique_pd_number_per_tenant')
        )
        op.create_index(op.f('ix_purchasedemand_number'), 'purchasedemand', ['number'], unique=False)
        op.create_index(op.f('ix_purchasedemand_tenant_id'), 'purchasedemand', ['tenant_id'], unique=False)

    if not bind.dialect.has_table(bind, 'purchasedemandline'):
        op.create_table('purchasedemandline',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('demand_id', sa.Integer(), nullable=False),
        sa.Column('product_id', sa.Integer(), nullable=True),
        sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('qty', sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(['demand_id'], ['purchasedemand.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
        sa.PrimaryKeyConstraint('id')
        )

    if not bind.dialect.has_table(bind, 'vendorquotation'):
        op.create_table('vendorquotation',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('tenant_id', sa.Integer(), nullable=False),
        sa.Column('number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('demand_id', sa.Integer(), nullable=False),
        sa.Column('vendor_id', sa.Integer(), nullable=False),
        sa.Column('quote_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('valid_until', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('delivery_terms', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('payment_terms', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['demand_id'], ['purchasedemand.id'], ),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
        sa.ForeignKeyConstraint(['vendor_id'], ['vendor.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('tenant_id', 'number', name='unique_vq_number_per_tenant')
        )
        op.create_index(op.f('ix_vendorquotation_demand_id'), 'vendorquotation', ['demand_id'], unique=False)
        op.create_index(op.f('ix_vendorquotation_number'), 'vendorquotation', ['number'], unique=False)
        op.create_index(op.f('ix_vendorquotation_tenant_id'), 'vendorquotation', ['tenant_id'], unique=False)

    if not bind.dialect.has_table(bind, 'vendorquotationline'):
        op.create_table('vendorquotationline',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('quotation_id', sa.Integer(), nullable=False),
        sa.Column('demand_line_id', sa.Integer(), nullable=False),
        sa.Column('rate', sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column('qty', sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
        sa.ForeignKeyConstraint(['demand_line_id'], ['purchasedemandline.id'], ),
        sa.ForeignKeyConstraint(['quotation_id'], ['vendorquotation.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )

    if not bind.dialect.has_table(bind, 'comparativestatement'):
        op.create_table('comparativestatement',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('tenant_id', sa.Integer(), nullable=False),
        sa.Column('number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('demand_id', sa.Integer(), nullable=False),
        sa.Column('cs_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('selected_quotation_id', sa.Integer(), nullable=True),
        sa.Column('justification', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('created_by_id', sa.Integer(), nullable=False),
        sa.Column('approved_by_id', sa.Integer(), nullable=True),
        sa.Column('approved_at', sa.DateTime(), nullable=True),
        sa.Column('po_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.CheckConstraint("status IN ('draft','approved','converted','cancelled')", name='ck_cs_status'),
        sa.ForeignKeyConstraint(['approved_by_id'], ['user.id'], ),
        sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
        sa.ForeignKeyConstraint(['demand_id'], ['purchasedemand.id'], ),
        sa.ForeignKeyConstraint(['po_id'], ['purchaseorder.id'], ),
        sa.ForeignKeyConstraint(['selected_quotation_id'], ['vendorquotation.id'], ),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('tenant_id', 'demand_id', name='unique_cs_per_demand'),
        sa.UniqueConstraint('tenant_id', 'number', name='unique_cs_number_per_tenant')
        )
        op.create_index(op.f('ix_comparativestatement_demand_id'), 'comparativestatement', ['demand_id'], unique=False)
        op.create_index(op.f('ix_comparativestatement_number'), 'comparativestatement', ['number'], unique=False)
        op.create_index(op.f('ix_comparativestatement_tenant_id'), 'comparativestatement', ['tenant_id'], unique=False)

    # SQLite can't ADD CONSTRAINT via ALTER — the FKs are enforced at the app
    # level only; create_foreign_key calls are stripped (see CLAUDE.md /
    # 5befc82a251f_invoice_cogs_transaction_id.py for the established pattern).
    po_cols = [c["name"] for c in sa.inspect(bind).get_columns("purchaseorder")]
    if "demand_id" not in po_cols:
        op.add_column('purchaseorder', sa.Column('demand_id', sa.Integer(), nullable=True))
    if "comparative_id" not in po_cols:
        op.add_column('purchaseorder', sa.Column('comparative_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    po_cols = [c["name"] for c in sa.inspect(bind).get_columns("purchaseorder")]
    if "comparative_id" in po_cols:
        op.drop_column('purchaseorder', 'comparative_id')
    if "demand_id" in po_cols:
        op.drop_column('purchaseorder', 'demand_id')

    if bind.dialect.has_table(bind, 'vendorquotationline'):
        op.drop_table('vendorquotationline')
    if bind.dialect.has_table(bind, 'vendorquotation'):
        op.drop_index(op.f('ix_vendorquotation_tenant_id'), table_name='vendorquotation')
        op.drop_index(op.f('ix_vendorquotation_number'), table_name='vendorquotation')
        op.drop_index(op.f('ix_vendorquotation_demand_id'), table_name='vendorquotation')
        op.drop_table('vendorquotation')
    if bind.dialect.has_table(bind, 'purchasedemandline'):
        op.drop_table('purchasedemandline')
    if bind.dialect.has_table(bind, 'purchasedemand'):
        op.drop_index(op.f('ix_purchasedemand_tenant_id'), table_name='purchasedemand')
        op.drop_index(op.f('ix_purchasedemand_number'), table_name='purchasedemand')
        op.drop_table('purchasedemand')
    if bind.dialect.has_table(bind, 'comparativestatement'):
        op.drop_index(op.f('ix_comparativestatement_tenant_id'), table_name='comparativestatement')
        op.drop_index(op.f('ix_comparativestatement_number'), table_name='comparativestatement')
        op.drop_index(op.f('ix_comparativestatement_demand_id'), table_name='comparativestatement')
        op.drop_table('comparativestatement')
    # ### end Alembic commands ###
