"""tenant_cost_method

Revision ID: 207cd883b6e6
Revises: e43e1c93c0c7
Create Date: 2026-05-28 21:57:39.608131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '207cd883b6e6'
down_revision: Union[str, Sequence[str], None] = 'e43e1c93c0c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant', sa.Column('cost_method', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenant', 'cost_method')
    # ### end Alembic commands ###
