"""budget

Revision ID: 2d98e7caa652
Revises: 207cd883b6e6
Create Date: 2026-05-28 22:04:53.703044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2d98e7caa652'
down_revision: Union[str, Sequence[str], None] = '207cd883b6e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('period_month', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.CheckConstraint('fiscal_year >= 2000 AND fiscal_year <= 2100', name='ck_budget_year'),
    sa.CheckConstraint('period_month >= 1 AND period_month <= 12', name='ck_budget_month'),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'account_id', 'fiscal_year', 'period_month', name='unique_budget_per_account_period')
    )
    op.create_index(op.f('ix_budget_tenant_id'), 'budget', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_budget_tenant_id'), table_name='budget')
    op.drop_table('budget')
    # ### end Alembic commands ###
