"""invoice cogs_transaction_id

Revision ID: 5befc82a251f
Revises: reportdef01
Create Date: 2026-06-05 22:56:30.798603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '5befc82a251f'
down_revision: Union[str, Sequence[str], None] = 'reportdef01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add the nullable cogs_transaction_id column. SQLite can't ADD CONSTRAINT
    # via ALTER (see CLAUDE.md), so the FK is enforced at the app level only —
    # the autogenerated create_foreign_key / unrelated FK lines are stripped.
    # Guard against re-runs / a column already present from create_all() boot.
    bind = op.get_bind()
    cols = [c["name"] for c in sa.inspect(bind).get_columns("invoice")]
    if "cogs_transaction_id" not in cols:
        op.add_column('invoice', sa.Column('cogs_transaction_id', sa.Integer(), nullable=True))


def downgrade() -> None:
    bind = op.get_bind()
    cols = [c["name"] for c in sa.inspect(bind).get_columns("invoice")]
    if "cogs_transaction_id" in cols:
        op.drop_column('invoice', 'cogs_transaction_id')
