"""deferred_revenue

Revision ID: 5df34b7550dd
Revises: a4b74eb2e919
Create Date: 2026-05-28 22:22:08.645735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5df34b7550dd'
down_revision: Union[str, Sequence[str], None] = 'a4b74eb2e919'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()

    if not bind.dialect.has_table(bind, 'deferredrevenueschedule'):
        op.create_table(
            'deferredrevenueschedule',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('tenant_id', sa.Integer(), nullable=False),
            sa.Column('invoice_id', sa.Integer(), nullable=False),
            sa.Column('total_amount', sa.Numeric(precision=18, scale=4), nullable=False),
            sa.Column('recognised_amount', sa.Numeric(precision=18, scale=4), nullable=False),
            sa.Column('start_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('end_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('frequency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('next_recognition_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('deferred_revenue_account_id', sa.Integer(), nullable=False),
            sa.Column('revenue_account_id', sa.Integer(), nullable=False),
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.CheckConstraint("frequency IN ('monthly','quarterly','yearly')", name='ck_deferred_freq'),
            sa.CheckConstraint("status IN ('active','completed','cancelled')", name='ck_deferred_status'),
            sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id']),
            sa.PrimaryKeyConstraint('id'),
        )
        op.create_index(op.f('ix_deferredrevenueschedule_tenant_id'), 'deferredrevenueschedule', ['tenant_id'], unique=False)

    # Add columns to product (safe guard)
    cols = {c['name'] for c in sa.inspect(bind).get_columns('product')}
    if 'is_deferred' not in cols:
        op.add_column('product', sa.Column('is_deferred', sa.Boolean(), nullable=False, server_default='0'))
    if 'recognition_months' not in cols:
        op.add_column('product', sa.Column('recognition_months', sa.Integer(), nullable=False, server_default='12'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'recognition_months')
    op.drop_column('product', 'is_deferred')
    op.drop_index(op.f('ix_deferredrevenueschedule_tenant_id'), table_name='deferredrevenueschedule')
    op.drop_table('deferredrevenueschedule')
    # ### end Alembic commands ###
