"""analytic_accounts

Revision ID: a4b74eb2e919
Revises: 8be90ae8a4a3
Create Date: 2026-05-28 22:10:50.140501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a4b74eb2e919'
down_revision: Union[str, Sequence[str], None] = '8be90ae8a4a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    if not bind.dialect.has_table(bind, 'analyticaccount'):
        op.create_table(
            'analyticaccount',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('tenant_id', sa.Integer(), nullable=False),
            sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('is_active', sa.Boolean(), nullable=False),
            sa.CheckConstraint("type IN ('cost_center','project','department')", name='ck_analytic_type'),
            sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id']),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('tenant_id', 'code', name='unique_analytic_code_per_tenant'),
        )
        op.create_index(op.f('ix_analyticaccount_tenant_id'), 'analyticaccount', ['tenant_id'], unique=False)

    # Add column to journalentry (safe to add if not exists)
    cols = {c['name'] for c in sa.inspect(bind).get_columns('journalentry')}
    if 'analytic_account_id' not in cols:
        op.add_column('journalentry', sa.Column('analytic_account_id', sa.Integer(), nullable=True))
    # FK constraint omitted: SQLite does not support ADD CONSTRAINT via ALTER TABLE.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('journalentry', 'analytic_account_id')
    op.drop_index(op.f('ix_analyticaccount_tenant_id'), table_name='analyticaccount')
    op.drop_table('analyticaccount')
    # ### end Alembic commands ###
