"""fixed_assets

Revision ID: e43e1c93c0c7
Revises: 1fcfbf29edfa
Create Date: 2026-05-28 21:53:04.778019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e43e1c93c0c7'
down_revision: Union[str, Sequence[str], None] = '1fcfbf29edfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fixedasset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('asset_account_id', sa.Integer(), nullable=False),
    sa.Column('accum_depr_account_id', sa.Integer(), nullable=False),
    sa.Column('depr_expense_account_id', sa.Integer(), nullable=False),
    sa.Column('acquisition_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('acquisition_cost', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('salvage_value', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('useful_life_months', sa.Integer(), nullable=False),
    sa.Column('method', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('accumulated_depreciation', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('book_value', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('is_disposed', sa.Boolean(), nullable=False),
    sa.Column('last_depreciation_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("method IN ('straight_line','reducing_balance')", name='ck_fixed_asset_method'),
    sa.ForeignKeyConstraint(['accum_depr_account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['asset_account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['depr_expense_account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fixedasset_tenant_id'), 'fixedasset', ['tenant_id'], unique=False)
    op.create_table('depreciationentry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('depreciation_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('depreciation_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['fixedasset.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_depreciationentry_tenant_id'), 'depreciationentry', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_depreciationentry_tenant_id'), table_name='depreciationentry')
    op.drop_table('depreciationentry')
    op.drop_index(op.f('ix_fixedasset_tenant_id'), table_name='fixedasset')
    op.drop_table('fixedasset')
    # ### end Alembic commands ###
